### ISSUE TITLE
'Enable automatic tab when max length in a input field is reached.' causes problems

### ISSUE THREAD

**Issue by benelot** [ThomasArdal/gInfinity#1]
'Enable automatic tab when max length in a input field is reached.' in my case leads to constant automatic tabbing in the case of pages like youtube or more local swiss pages like salt.ch. Of course the problem is fixed by turning the feature off. Probably make the feature turned off by default. Or do you think that there is an actual issue to be fixed? Probably you are reacting wrongly to a missing max length tag or one that is changed by a script.

**Comment by ThomasArdal** [comment]
@benelot You may have a point. Unfortunately, I'm not maintaining this repo anymore. Could you make a pull request?

**Comment by benelot** [comment]
I made a pull request for you. Can you review it? I think it does the right thing, but you might remember better. Can you update the extension in in the extensions store?
